# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-06 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lawdcd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawdcd',
            options={'managed': False},
        ),
    ]
